/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class Tela_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Tela_GUI
     */
    public Tela_GUI() {
        initComponents();
        res_txt.setVisible(false);
        img_img.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        dividir_btn = new javax.swing.JButton();
        somar_btn = new javax.swing.JButton();
        limpar_btn = new javax.swing.JButton();
        multiplicar_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        valor1_txt = new javax.swing.JTextField();
        valor2_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Sair_btn = new javax.swing.JButton();
        res_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        subtrair_btn = new javax.swing.JButton();
        img_img = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(223, 247, 224));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        dividir_btn.setBackground(new java.awt.Color(180, 202, 180));
        dividir_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dividir_btn.setText("/");
        dividir_btn.setToolTipText("");
        dividir_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dividir_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dividir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividir_btnActionPerformed(evt);
            }
        });
        jPanel2.add(dividir_btn);
        dividir_btn.setBounds(240, 300, 150, 60);

        somar_btn.setBackground(new java.awt.Color(180, 202, 180));
        somar_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        somar_btn.setText("+");
        somar_btn.setToolTipText("");
        somar_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        somar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        somar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(somar_btn);
        somar_btn.setBounds(50, 220, 150, 60);

        limpar_btn.setBackground(new java.awt.Color(224, 97, 97));
        limpar_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        limpar_btn.setText("C");
        limpar_btn.setToolTipText("");
        limpar_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        limpar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(limpar_btn);
        limpar_btn.setBounds(300, 180, 60, 30);

        multiplicar_btn.setBackground(new java.awt.Color(180, 202, 180));
        multiplicar_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        multiplicar_btn.setText("X");
        multiplicar_btn.setToolTipText("");
        multiplicar_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        multiplicar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiplicar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(multiplicar_btn);
        multiplicar_btn.setBounds(50, 300, 150, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CALCULADORA");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 10, 120, 29);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Valor 1:");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        valor1_txt.setBackground(new java.awt.Color(144, 171, 149));
        valor1_txt.setToolTipText("Utilize ponto em vez de vírgula para separação");
        valor1_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(valor1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 280, 30));

        valor2_txt.setBackground(new java.awt.Color(144, 171, 149));
        valor2_txt.setToolTipText("Utilize ponto em vez de vírgula para separação");
        valor2_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(valor2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 280, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Valor 2:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 62, 50));

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 50, 390, 120);

        Sair_btn.setBackground(new java.awt.Color(207, 39, 39));
        Sair_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sair_btn.setForeground(new java.awt.Color(255, 255, 255));
        Sair_btn.setText("X");
        Sair_btn.setBorder(null);
        Sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Sair_btn);
        Sair_btn.setBounds(400, 0, 30, 23);

        res_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_txtActionPerformed(evt);
            }
        });
        jPanel2.add(res_txt);
        res_txt.setBounds(180, 180, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Resultado:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 180, 100, 20);

        subtrair_btn.setBackground(new java.awt.Color(180, 202, 180));
        subtrair_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subtrair_btn.setText("-");
        subtrair_btn.setToolTipText("");
        subtrair_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        subtrair_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subtrair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtrair_btnActionPerformed(evt);
            }
        });
        jPanel2.add(subtrair_btn);
        subtrair_btn.setBounds(240, 220, 150, 60);

        img_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kirby.png"))); // NOI18N
        jPanel2.add(img_img);
        img_img.setBounds(10, 10, 20, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(427, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dividir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividir_btnActionPerformed
        Controller.Funcoes_DAO.divisao();
    }//GEN-LAST:event_dividir_btnActionPerformed

    private void somar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somar_btnActionPerformed
        Controller.Funcoes_DAO.somar();
    }//GEN-LAST:event_somar_btnActionPerformed
    private void limpar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_btnActionPerformed
        Controller.Funcoes_DAO.limpar();
    }//GEN-LAST:event_limpar_btnActionPerformed

    private void multiplicar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicar_btnActionPerformed
        Controller.Funcoes_DAO.multiplicacao();
    }//GEN-LAST:event_multiplicar_btnActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void Sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Sair_btnActionPerformed

    private void res_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res_txtActionPerformed

    private void subtrair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtrair_btnActionPerformed
        Controller.Funcoes_DAO.subtrair();
    }//GEN-LAST:event_subtrair_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair_btn;
    public static javax.swing.JButton dividir_btn;
    public static javax.swing.JLabel img_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JButton limpar_btn;
    public static javax.swing.JButton multiplicar_btn;
    public static javax.swing.JTextField res_txt;
    public static javax.swing.JButton somar_btn;
    public static javax.swing.JButton subtrair_btn;
    public static javax.swing.JTextField valor1_txt;
    public static javax.swing.JTextField valor2_txt;
    // End of variables declaration//GEN-END:variables
}
